// COUNTER GETTERS
export const DOUBLE_COUNTER = 'counter/DOUBLE_COUBTER';
export const CLICKS_COUNTER = 'counter/CLICKS_COUNTER';
export const INPUT_VALUE    = 'shared/INPUT_VALUE';

// COUNTER MUTATIONS
export const MUTATIONS_INC_COUNTER  = 'counter/MUTATIONS_INC_COUNTER';
export const MUTATIONS_DEC_COUNTER  = 'counter/MUTATIONS_DEC_COUNTER';
export const MUTATIONS_UPDATE_VALUE = 'counter/MUTATIONS_DEC_COUNTER';
export const MUTATIONS_INPUT_VALUE  = 'shared/MUTATIONS_INPUT_VALUE';

// COUNTER ACTIONS
export const ACTIONS_INC_COUNTER       = 'counter/ACTIONS_INC_COUNTER';
export const ACTIONS_INC_COUNTER_ASYNC = 'counter/ACTIONS_INC_COUNTER_ASYNC';
export const ACTIONS_DEC_COUNTER       = 'counter/ACTIONS_DEC_COUNTER';
export const ACTIONS_DEC_COUNTER_ASYNC = 'counter/ACTIONS_DEC_COUNTER_ASYNC';
export const ACTIONS_INPUT_VALUE       = 'shared/MUTATIONS_INPUT_VALUE';